
server:
  port: 8092

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wqb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: chingi200102


Logging:
  level:
    com.wms: debug




